affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - x
  - x
- - '0'
  - '0'
- - x
  - exp
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - exp
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - x
  - log
- - exp
  - x
- - x
  - x
- - exp
  - exp
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - exp
  - x
- - exp
  - log
- - x
  - x
- - '0'
  - '0'
- - exp
  - x
- - x
  - x
- - x
  - log
- - x
  - x
- - '0'
  - '0'
- - log
  - x
- - x
  - x
- - x
  - x
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - log
- - exp
  - x
- - x
  - exp
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - exp
- - x
  - x
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - '0'
  - '0'
- - x
  - x
- - '0'
  - '0'
- - '0'
  - '0'
- - x
  - x
- - '0'
  - '0'
- - exp
  - x
- - x
  - x
- - x
  - x
- - x
  - log
- - x
  - log
- - '0'
  - '0'
- - '0'
  - '0'
- - x
  - exp
- - '0'
  - '0'
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - exp
  - x
- - '0'
  - '0'
- - log
  - x
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - '0'
  - '0'
- - exp
  - log
- - x
  - exp
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - '0'
  - '0'
- - x
  - x
- - x
  - x
- - x
  - x
- - x
  - x
- - '0'
  - '0'
- - x
  - x
- - x
  - log
- - x
  - x
symbolic.funs_name.1:
- - x
  - '0'
  - x
  - '0'
  - exp
  - x
  - x
  - '0'
  - exp
  - x
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - exp
  - x
  - '0'
  - x
  - x
  - x
  - x
  - '0'
  - exp
  - x
  - x
  - x
  - x
  - '0'
  - exp
  - x
  - exp
  - x
  - x
  - '0'
  - exp
  - x
  - x
  - x
  - exp
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - x
  - '0'
  - x
  - '0'
  - exp
  - exp
  - '0'
  - x
  - exp
  - x
  - '0'
  - '0'
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
symbolic_enabled: true
width:
- - 2
  - 0
- - 100
  - 0
- - 1
  - 0
