affine_trainable: false
auto_save: true
base_fun_name: zero
ckpt_path: ./model
device: cpu
grid: 200
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: false
sp_trainable: false
state_id: 5
symbolic.funs_name.0:
- - '0'
symbolic_enabled: false
width:
- - 1
  - 0
- - 1
  - 0
